version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typedoc
    versions:
    - ">= 0.15.0.a, < 0.15.1"
